name: Python Selenium CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  selenium-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'  # Specify your Python version

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install webdriver-manager  # Ensure this is included for automatic ChromeDriver management
        pip install pytest
        

    - name: Install Chrome
      run: |
        sudo apt-get update
        sudo apt-get install -y chromium-browser

    - name: Run Pytest
      run: |
        pytest tests/  # Run tests in the 'tests/' directory
