name: Python Selenium CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  selenium-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install webdriver-manager

    - name: Install Chrome
      run: |
        sudo apt-get update
        sudo apt-get install -y chromium-browser

    - name: Install Compatible ChromeDriver
      run: |
        # Set a fixed version for ChromeDriver that is known to work
        CHROME_VERSION=113  # Choose a version known to have support, e.g., 113
        CHROMEDRIVER_VERSION=$(curl -s "https://chromedriver.storage.googleapis.com/LATEST_RELEASE_${CHROME_VERSION}")
        echo "Chrome version: $CHROME_VERSION"
        echo "ChromeDriver version: $CHROMEDRIVER_VERSION"
        wget "https://chromedriver.storage.googleapis.com/${CHROMEDRIVER_VERSION}/chromedriver_linux64.zip"
        unzip chromedriver_linux64.zip -d /usr/local/bin/

    - name: Run Pytest
      run: |
        pytest tests/
