name: Selenium CI/CD Demo

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest openpyxl selenium webdriver-manager openai

      - name: Install headless browser dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libnss3 \
            libxi6 \
            libxcursor1 \
            libxrandr2 \
            libxss1 \
            libatk1.0-0 \
            libatk-bridge2.0-0 \
            libcups2 \
            libgbm-dev

      - name: Run Pytest
        run: |
          pytest tests/ --maxfail=3 --disable-warnings -v

      - name: Ensure artifacts exist
        run: |
          mkdir -p screenshots
          touch login_test_log.xlsx

      - name: Upload test screenshots and Excel log
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-artifacts
          path: |
            screenshots/
            login_test_log.xlsx
